---
- name: "Install the correct repository"
  import_tasks: "redhat.yml"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: "Install the correct repository"
  import_tasks: "ubuntu.yml"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
